version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - yugi-commerce

  hyperspace:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - yugi-commerce

networks:
  yugi-commerce:
